import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Date Scheduler",
  description: "Generated by create next app",
};
const customFont = localFont({
  src: [
    {
      path: '../../public/fonts/GourmetEatery-V4qdw.otf',
      weight: '400',
      style: 'normal',
    }
  ],
  variable: "--font-gourmet-eatery", 
});
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${customFont.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
